// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSy4w5q9wFHipBKflRPMuG8rpRMHR4fJU',
    appId: '1:75475075281:web:5b99b8fe80cabdad7c85f0',
    messagingSenderId: '75475075281',
    projectId: 'appdev-1541e',
    authDomain: 'appdev-1541e.firebaseapp.com',
    storageBucket: 'appdev-1541e.appspot.com',
    measurementId: 'G-6F22S5429K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtMBoHlna9HN1cm5aMkpcHQkVkks3tRHw',
    appId: '1:75475075281:android:26a28bafd3ba98427c85f0',
    messagingSenderId: '75475075281',
    projectId: 'appdev-1541e',
    storageBucket: 'appdev-1541e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUgcWEvHYkVm0s5Z-wQOuBFaxRLJP5L_A',
    appId: '1:75475075281:ios:0f3b327d821dd1137c85f0',
    messagingSenderId: '75475075281',
    projectId: 'appdev-1541e',
    storageBucket: 'appdev-1541e.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUgcWEvHYkVm0s5Z-wQOuBFaxRLJP5L_A',
    appId: '1:75475075281:ios:3a66b98c154aac147c85f0',
    messagingSenderId: '75475075281',
    projectId: 'appdev-1541e',
    storageBucket: 'appdev-1541e.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
